const GITHUB_PROFILE = {
  login: "omonteon",
  id: 2767295,
  node_id: "MDQ6VXNlcjI3NjcyOTU=",
  avatar_url: "https://avatars.githubusercontent.com/u/2767295?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/omonteon",
  html_url: "https://github.com/omonteon",
  followers_url: "https://api.github.com/users/omonteon/followers",
  following_url: "https://api.github.com/users/omonteon/following{/other_user}",
  gists_url: "https://api.github.com/users/omonteon/gists{/gist_id}",
  starred_url: "https://api.github.com/users/omonteon/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/omonteon/subscriptions",
  organizations_url: "https://api.github.com/users/omonteon/orgs",
  repos_url: "https://api.github.com/users/omonteon/repos",
  events_url: "https://api.github.com/users/omonteon/events{/privacy}",
  received_events_url: "https://api.github.com/users/omonteon/received_events",
  type: "User",
  site_admin: false,
  name: "Monty",
  company: "Avena Mexico",
  blog: "https://linkedin.com/in/omonteon",
  location: "Guadalajara, México",
  email: null,
  hireable: null,
  bio: "Software engineer. Frontend development is my current focus.",
  twitter_username: null,
  public_repos: 12,
  public_gists: 0,
  followers: 6,
  following: 5,
  created_at: "2012-11-10T17:33:03Z",
  updated_at: "2022-08-18T03:22:47Z",
};

export { GITHUB_PROFILE };
